<?php
include 'conf.php';  

$wq = "SELECT * FROM ogrn WHERE id=(SELECT MAX(id) FROM ogrn)";
$wresult = mysql_query($wq);
$wperson = mysql_fetch_array($wresult);
$wq2 = "SELECT * FROM klient WHERE id=(SELECT MAX(id) FROM klient)";
$wresult2 = mysql_query($wq2);
$wperson2 = mysql_fetch_array($wresult2);

if (isset($_COOKIE['id']) and isset($_COOKIE['hash'])) 
{
$userdata = mysql_fetch_assoc(mysql_query("SELECT * FROM users WHERE users_id = '".intval($_COOKIE['id'])."' LIMIT 1"));if(($userdata['users_hash'] !== $_COOKIE['hash']) or ($userdata['users_id'] !== $_COOKIE['id'])) 
{ 
setcookie('id', '', time() - 60*24*30*12, '/'); 
setcookie('hash', '', time() - 60*24*30*12, '/');
setcookie('errors', '1', time() + 60*24*30*12, '/'); 
header('Location: index.php'); exit();
} 
} 
else 
{ 
  setcookie('errors', '2', time() + 60*24*30*12, '/');
  header('Location: index.php'); exit();
}
if($_GET['id'] != 0){
$kliz = "SELECT * FROM call_center WHERE id = '".$_GET['id']."'";
$kliresultz = mysql_query($kliz);
$klientz = mysql_fetch_array($kliresultz);
if($klientz['3'] == "0"){
$klizz = "SELECT COUNT(*) FROM call_center ";
$kliresultzz = mysql_query($klizz);
/* if (mysql_result($kliresultzz, 0) >= 15){
echo '<div class="alert alert-danger" role="alert" style="text-align: center;font-size: 17px;">Вы взяли максимальное количество клиентов в обработку, сначала завершите обработку!!!</div>';
}else{
mysql_query("UPDATE `call_center` SET `3` =  '".$userdata['users_id']."' WHERE id ='".$_GET['id']."'");
} */
$kli = "SELECT * FROM call_center WHERE id = '".$_GET['id']."'";
$kliresult = mysql_query($kli);
$klient = mysql_fetch_array($kliresult);
}else{
$kli = "SELECT * FROM call_center WHERE id = '".$_GET['id']."'";
$kliresult = mysql_query($kli);
$klient = mysql_fetch_array($kliresult);
}
}else{
$kli = "SELECT * FROM call_center WHERE id = '".$_GET['id']."'";
$kliresult = mysql_query($kli);
$klient = mysql_fetch_array($kliresult);
} 

$q = "SELECT * FROM ogrn WHERE id ='".$klient['idogrn']."'";
$result = mysql_query($q);
$ogrn = mysql_fetch_array($result);

$issetkomment = mysql_query("SELECT COUNT(*) FROM ogrn WHERE id ='".$klient['idogrn']."'");
$yesogrn = mysql_result($issetkomment, 0);

 ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
<meta http-equiv="content-type" content="text/html" charset="utf-8" />
<link href="css/bootstrap.min.css" rel="stylesheet">
<meta name="description" content="An Icon Font Generated By IcoMoon.io">
<meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="style.css"> 
<link href="https://dadata.ru/static/css/lib/suggestions-4.8.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="https://dadata.ru/static/js/lib/jquery.suggestions-4.8.min.js"></script>
</head>
<body style="background: #F5F5F5;color: #666;">
<div style="margin-bottom: 8px;font-size: 18px;background: #3b5998;padding: 5px 13px;color: #fff;">
Обзвон клиентов <?php if($schet['oferta'] == 1){echo  '-ОФЕРТА';} echo ' '.$schet['god'].$schet['filial'].$schet['otdel'].$pfsdhhgf['id'].$schet['nomerschet'];?>
</div>
<div class="container">
<div class="row">
<div class="col-md-12" style="padding: 10px;margin: 0 -7px;">
<div class="input-group" style="padding: 0 5px;">
<?php 
		if($yesogrn == 0){
		echo '<span class="input-group-addon" style="background: #fff;font-size: 20px;padding: 0 10px;"><span class="icon-search"></span></span>
<input class="form-control suggestions-input" id="party" name="party" value="'.$klient['9'].'" type="text" style="box-sizing: border-box; padding-left: 7px; padding-right: 7px; height: 36px; border-color: rgb(204, 204, 204); border-bottom-right-radius: 4px; border-top-right-radius: 4px; font-size: 18px;" autocomplete="off"><div class="suggestions-wrapper"></div>';
}?>
<script type="text/javascript">
$("#party").suggestions({
serviceUrl: "https://dadata.ru/api/v2",
token: "b955dbc625a2b4895757691d955ff2e983a46f1c",
type: "PARTY",
count: 7,
onSelect: showSelected
});
function join(arr /*, separator */) {
var separator = arguments.length > 1 ? arguments[1] : ", ";
return arr.filter(function(n){return n}).join(separator);
}function showSelected(suggestion) {
var party = suggestion.data;
 
$("#tip").val(
join([party.opf.full + ' "' + party.name.full+'"'], " ")
);

if(suggestion.data.opf.short == null){
	$("#naim").val(suggestion.value);
}else{
	$("#naim").val(suggestion.data.opf.short+' "'+suggestion.data.name.full+'"');
}

if(suggestion.data.opf.code == 50102){
	 suka = $("#name").val(join([party.name.full], " "));
	$("#name").val(join([party.name.full], " "));
}else{
	 suka = $("#name").val(join([party.management.name], " "));
	$("#name").val(join([party.management.name], " "));
}
$("#uridadress").val(
join([party.address && party.address.value || ""], " ")
);
$("#ogrn").val(
join([party.ogrn], " ")
);
<?php 
if(strlen($klient['2']) == '0'){
echo '$("#inn").val(
join([party.inn], " ")
);';
}
?>
$("#okved").val(
join([party.okved], " ")
);
$("#kpp").val(
join([party.kpp], " ")
);

if(suka == '<?php echo $klient['17'];?>'){
document.getElementById("namehorizontal").style.display="none";
}

}
</script>
</div>
<div class="col-md-4">
<p><h4>Информация о заказчике</h4></p>


		
		<?php
		if($yesogrn != 0){
		echo '<div class="alert alert-success text-center">Организация уже существует в базе данных! &nbsp; &nbsp;<a  target="_blank" href="/kartklient.php?id='.$ogrn['id'].'" class="btn btn-success btn-xs">ОТКРЫТЬ</a></div>';
		echo'<form class="form-horizontal">';
		if(!empty($ogrn['naim'])){
			echo'<div class="form-group">
				<label class="col-sm-3 control-label">Наименование:</label><div class="col-sm-9"><p class="form-control-static">'.$ogrn['naim'].'</p></div>		
			</div>';
		}if(!empty($ogrn['ogrn'])){
			echo'<div class="form-group">
				<label class="col-sm-3 control-label">ОГРН:</label><div class="col-sm-9"><p class="form-control-static">'.$ogrn['ogrn'].'</p></div>		
			</div>';
		}if(!empty($ogrn['inn'])){
			echo'<div class="form-group">
				<label class="col-sm-3 control-label">ИНН:</label><div class="col-sm-9"><p class="form-control-static">'.$ogrn['inn'].'</p></div>		
			</div>';
		}if(!empty($ogrn['kpp'])){
			echo'<div class="form-group">
				<label class="col-sm-3 control-label">КПП:</label><div class="col-sm-9"><p class="form-control-static">'.$ogrn['kpp'].'</p></div>		
			</div>';
		}if(!empty($ogrn['uridadress'])){
			echo'<div class="form-group">
				<label class="col-sm-3 control-label">Ю. адрес:</label><div class="col-sm-9"><p class="form-control-static">'.$ogrn['uridadress'].'</p></div>		
			</div>';
		}if(!empty($ogrn['fakadress'])){
			echo'<div class="form-group">
				<label class="col-sm-3 control-label">Ф. адрес:</label><div class="col-sm-9"><p class="form-control-static">'.$ogrn['fakadress'].'</p></div>		
			</div>';
		}	
		
		
				echo'<h4>Контакты</h4>
		<table class="table">
		
		<thead>
		<tr>
		  <th>ФИО: </th>
		  <th>Должность: </th>
		  <th>Телефон: </th>
		  <th>E-mail: </th>
		  <th></th>
		  <th></th>
		  <th></th>
		</tr>
		</thead>
		
		';
	
		$a = 1;
		$query2 = mysql_query("SELECT * from klient_ogrn WHERE idkli = '".$ogrn['id']."' ORDER BY id DESC");	
		while($row2 = mysql_fetch_array($query2)) {
		$query3 = mysql_query("SELECT * from klient WHERE id = '".$row2['klient']."' ORDER BY id DESC");	
		while($row3 = mysql_fetch_array($query3)) {
		echo '<tr>';
		echo '<td>';
		echo '',$row3['fio'];
		echo '</td>';
		echo '<td>';
		echo '',$row3['dol'];
		echo '</td>';
		echo '<td>';
		echo ''.$row3['tel'].'</td>';
		echo '<td>';
		echo '',$row3['email'];
		echo '</td>';
		echo '<td>';
		echo '<li role="presentation" class="dropdown">
        <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
          <span class="glyphicon glyphicon-earphone"></span>
          <span class="caret"></span>
        </a>
        <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4" style="right: 0;left: inherit;">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="">Позвонить</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="">Принял звонок</a></li>
          <li role="presentation" class="divider"></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href=""><span style="color: red;" class="glyphicon glyphicon-stop" aria-hidden="true"></span> Не дозвонился</a></li>
        </ul>
      </li>';
		echo '</td>';
		echo '<td>';
		echo '<li role="presentation" class="dropdown">
        <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
          <span class="glyphicon glyphicon-envelope"></span>
          <span class="caret"></span>
        </a>
        <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4" style="right: 0;left: inherit;">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="">Отправить СМС</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="">Отправить E-mail</a></li>
          <li role="presentation" class="divider"></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href=""><span style="color: red;" class="glyphicon glyphicon-stop" aria-hidden="true"></span> Не дошло</a></li>
        </ul>
      </li>';
		echo '</td>';
		echo '<td>';

		echo '<button style="margin-bottom: 6px;" type="button" class="" data-toggle="modal" data-target="#modal'.$row3['id'].'">
<span class="icon-wrench"></span></button>

<div id="modal'.$row3['id'].'" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" style="
    width: 600px;
    margin: 30px auto;
">
    <div class="modal-content">
<form action="'.$_SERVER['REQUEST_URI'].'" method="post">
<div class="col-md-12">
<div style="background: #ddd; padding: 6px; padding-top: 0;margin-top: 10px;border-radius: 5px;"><strong><h4 style="border-bottom: 1px #FFF solid; font-weight: bold;background: #5D75A8;padding: 4px 6px;border-radius: 3px;border-bottom-left-radius: 0;border-bottom-right-radius: 0;color: #fff;margin: 0px -5px 6px -5px;padding-bottom: 4px;"><span class="icon-user4"></span> Контактное лицо</h4></strong><div class="input-group">
<span class="input-group-addon">ФИО:</span>
<input class="form-control" name="fio" type="text" id="fio" value="'.$row3['fio'].'" style="box-sizing: border-box; border-color: rgb(204, 204, 204); border-bottom-right-radius: 4px; border-top-right-radius: 4px; padding-left: 7px;"> 
</div>
<div style="margin-top: 6px;"></div><div class="input-group">
<span class="input-group-addon">Должность:</span> 
<input id="dol" type="text" name="dol"class="form-control"  value="'.$row3['dol'].'" />
</div>
<div style="margin-top: 6px;"></div>
<div class="input-group">
<span class="input-group-addon">Телефон:</span> 
<input  class="form-control" type="tel" required pattern="[0-9_\-]{10}" placeholder="+7(___) ___ __ __" id="user_phone99" name="tel"  value="'.$row3['tel'].'" />
</div>
<div style="margin-top: 6px;"></div>
<div class="input-group">
<span class="input-group-addon">E-mail:</span>
<input id="email" class="form-control" type="text"name="email"  value="'.$row3['email'].'" />
</div>
<div style="margin-top: 6px;"></div>
<div class="input-group">
<span class="input-group-addon">На оснований:</span>
<input id="naosnovanii" class="form-control" type="text"name="naosnovanii"  value="'.$row3['naosnovanii'].'" />
</div>
</div>
</div>

<input type="submit" name="nksubmitw'.$row3['id'].'" value="Редактировать" class="btn btn-success" role="button" style="
    margin-left: 5px;
    margin-top: -5px;
    padding-top: 10px;
    border: none;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
">
<input type="submit" name="nkdel'.$row3['id'].'" value="Удалить" class="btn btn-primary" role="button" style="
    margin-left: 5px;
    margin-top: -5px;
    padding-top: 10px;
    border: none;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
">

</form>
    </div>
  </div>
</div>

';

if(isset($_POST['nksubmitw'.$row3['id']])){
$licoetw = "UPDATE `klient` SET `fio`='$_POST[fio]',`dol`='$_POST[dol]',`tel`='$_POST[tel]',`email`='$_POST[email]',`naosnovanii`='$_POST[naosnovanii]' WHERE id =".$row3['id'];
mysql_query($licoetw) or die(mysql_error($links));
echo '<script type="text/javascript">
   document.location.href = "'.$_SERVER['REQUEST_URI'].'";
</script>';
}if(isset($_POST['nkdel'.$row3['id']])){
$licoetw = "DELETE FROM `klient` WHERE id =".$row3['id'];
mysql_query($licoetw) or die(mysql_error($links));
echo '<script type="text/javascript">
   document.location.href = "'.$_SERVER['REQUEST_URI'].'";
</script>';
}
echo '</td>';
echo '</tr>';
}
}
echo'</table>';
}else{
	
	
	
	
echo '<form class="form-horizontal" action="'.$_SERVER['REQUEST_URI'].'" method="post">
	<div class="form-group">
		<label class="col-sm-3 control-label">Наименование:</label>';
		if(empty($klient['8'])){
			echo '<div class="col-sm-9"><input id="naim" name="naim" class="form-control col-90" type="text" placeholder="'.$klient['8'].'" aria-describedby="basic-addon1"></div>';
		}else{
			echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['8'].'</p></div>';
			echo '<div class="col-sm-9 none"><input id="naim" name="naim" class="form-control col-90" type="text" placeholder="'.$klient['8'].'" aria-describedby="basic-addon1"></div>';
		}
		echo '
	</div>
<div class="form-group has-warning has-feedback" id="ogrn91">
	<label class="col-sm-3 control-label">ОГРН:</label>';
	if(empty($klient['ogrn'])){
		echo '<div class="col-sm-9"><input class="form-control col-90" id="ogrn" name="ogrn" type="text" maxlength="15" required="" pattern="[0-9]{13,15}" aria-describedby="basic-addon1" ><span id="ogrn911" class="" style="z-index: 99; margin-top: -3px;"></span></div>';
	}else{
		echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['ogrn'].'</p></div>';}
	echo '<script language="javascript">
	var input = document.getElementById("ogrn");
	input.oncut = input.oncopy = input.onpaste = input.onfocus = input.onblur = input.onkeyup = input.oninput = input.onchange = input.onpropertychange = function() {
	number = $("input[id=\'ogrn\']").val().length;
	$("#ogrn911").load(" #ogrn911");
	if (number==13 || number==15){
	document.getElementById("ogrn91").className = "form-group has-success has-feedback";
	document.getElementById("ogrn911").className = "glyphicon glyphicon-ok form-control-feedback";
	}if (number<13 || number==14){
	document.getElementById("ogrn91").className = "form-group has-warning has-feedback";
	document.getElementById("ogrn911").className = "glyphicon glyphicon-warning-sign form-control-feedback";
	}};</script>
</div>
<div class="form-group">
<label class="col-sm-3 control-label">ИНН:</label>';
if(empty($klient['9'])){
	echo '<div class="col-sm-9"><input class="form-control col-90" type="text" id="inn" name="inn" placeholder="" aria-describedby="basic-addon1" ></div>';
}else{
	echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['9'].'</p></div>';
	echo '<div class="col-sm-9 none"><input class="form-control col-90" type="text" id="inn" name="inn" placeholder="" aria-describedby="basic-addon1" ></div>';
}
echo '</div>';
if(strlen($klient['9']) == '10' || strlen($klient['9']) == '0'){
echo '<div class="form-group">
<label class="col-sm-3 control-label">КПП:</label>';
if(empty($klient['10'])){
	echo '<div class="col-sm-9"><input class="form-control col-90" type="text" id="kpp" name="kpp" placeholder="'.$klient['10'].'" aria-describedby="basic-addon1" ></div>';
}else{
	echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['10'].'</p></div>';
	echo '<div class="col-sm-9 none"><input class="form-control col-90" type="text" id="kpp" name="kpp" placeholder="'.$klient['10'].'" aria-describedby="basic-addon1" ></div>';
}
echo '</div>';
}		
echo '
<div class="form-group">
<label class="col-sm-3 control-label">ОКВЭД:</label>';
if(empty($klient['22'])){
	echo '<div class="col-sm-9"><input class="form-control col-90" id="okved" type="text" name="okved" placeholder="00.0" aria-describedby="basic-addon1" ></div>';
}else{
	echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['22'].'</p></div>';
	echo '<div class="col-sm-9" none><input class="form-control col-90" id="okved" type="text" name="okved" placeholder="00.0" aria-describedby="basic-addon1" ></div>';
}
echo '</div>
<div class="form-group">
<label class="col-sm-3 control-label">Web:</label>';
if(empty($klient['23'])){
	echo '<div class="col-sm-9"><input class="form-control col-90" type="text" placeholder="gmcrm.ru" name="site" aria-describedby="basic-addon1" ></div>';
}else{
	echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['23'].'</p></div>';
	echo '<div class="col-sm-9" none><input class="form-control col-90" type="text" placeholder="gmcrm.ru" name="site" aria-describedby="basic-addon1" ></div>';
}
echo '</div>
<div class="form-group has-warning has-feedback">
<label class="col-sm-3 control-label">Ю. Адрес:</label>';
if(empty($klient['24'])){
	echo '<div class="col-sm-9"><input id="uridadress" name="uridadress" class="form-control col-90" type="text" placeholder="г. Пятигорск ул. Ермолова 38/1" aria-describedby="basic-addon1" ></div>';
}else{
	echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['24'].'</p></div>';
}
echo '</div>
<div class="form-group">
<label class="col-sm-3 control-label">Ф. Адрес:</label>';
if(empty($klient['25'])){
	echo '<div class="col-sm-9"><input class="form-control col-90" name="fakadress" type="text" placeholder="г. Пятигорск ул. Ермолова 38/1" aria-describedby="basic-addon1" ></div>';
}else{
	echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['25'].'</p></div>';
}
echo '</div>';
echo'<div>';
echo ''.$klient['25'].'';
echo'</div>';
echo'<p><h4>Контактные данные: <select class="" name="dol" style="border: none;  background-color: #F5F5F5;"> <option>Руководитель</option><option>Сотрудник</option><option>Заместитель</option><option>Секретарь</option><option>Бухгалтер</option><option>Программист</option><option>Юрист</option><option>Другой</option></select>
<div id="show" style="float: right;font-size: 13px;margin-top: 7px;  cursor: pointer;">Добавить ещё</div></h4></p> 
<div class="form-group">
<label class="col-sm-3 control-label">ФИО:</label>';

	echo '<div class="col-sm-9"><input class="form-control col-90" id="name" name="fio" type="text" placeholder="Петров Петр Петрович" aria-describedby="basic-addon1"></div>';

echo '</div><div class="form-group">
<label class="col-sm-3 control-label">Email:</label>';

	echo '<div class="col-sm-9"><input class="form-control col-90" name="email" type="text" placeholder="gmrx@mail.ru" aria-describedby="basic-addon1" ></div>';

echo '</div>
<div class="form-group">';
if(empty($klient['99'])){
			echo '<label class="col-sm-3 control-label">Тел.:</label>
				<div class="col-sm-9">
					<div class="input-group col-90">
						<select  class="form-control" style="float: left;width: 30%;"><option>Рабочий</option><option>Раб.прямой</option><option>Мобильный</option><option>Факс</option><option>Городской</option><option>Другой</option></select>
							<input class="form-control" style="float: left;width: 70%;" type="tel" name="tel" required pattern="[0-9_\-]{10}" placeholder="+7(___) ___ __ __" id="iuser_phone2" title="Формат: (096) 999 99 99">
					</div>
				</div>';
			}else{
				echo '';
				$vowels = array("+", "(", ")", " ", "-", ",", "", "а", "б", "в", "г", "д", "е", "ё", "ж", "з", "и", "й", "к", "л", "м", "н", "о", "п", "р", "с", "т", "у", "ф", "х", "ц", "ч", "ш", "щ", "ъ", "ы", "ь", "э", "ю", "я", "А", "Б", "В", "Г", "Д", "Е", "Ё", "Ж", "З", "И", "Й", "К", "Л", "М", "Н", "О", "П", "Р", "С", "Т", "У", "Ф", "Х", "Ц", "Ч", "Ш", "Щ", "Ъ", "Ы", "Ь", "Э", "Ю", "Я");
				$old = str_replace($vowels, "", $klient['18']);
				$newtext = explode(';', $old, -1); 
				if(isset($newtext[0])){echo '<label class="col-sm-3 control-label">Тел.:</label><div class="col-sm-9"><p class="form-control-static"style="color: #FFF;background-color: #77C877; width: 94px;padding: 4px;float: left;">'.$newtext[0].' </p><span style="padding: 4px; margin-top: -1px;" class="hidee btn btn-success glyphicon glyphicon-earphone" aria-hidden="true"></span></div>';}
				if(isset($newtext[1])){echo '<label class="col-sm-3 control-label">Тел.:</label><div class="col-sm-9"><p class="form-control-static"style="color: #FFF;background-color: #77C877; width: 94px;padding: 4px;float: left;">'.$newtext[1].' </p><span style="padding: 4px; margin-top: -1px;" class="hidee btn btn-success glyphicon glyphicon-earphone" aria-hidden="true"></span></div>';}
				if(isset($newtext[2])){echo '<label class="col-sm-3 control-label">Тел.:</label><div class="col-sm-9"><p class="form-control-static"style="color: #FFF;background-color: #77C877; width: 94px;padding: 4px;float: left;">'.$newtext[2].' </p><span style="padding: 4px; margin-top: -1px;" class="hidee btn btn-success glyphicon glyphicon-earphone" aria-hidden="true"></span></div>';}
				if(isset($newtext[3])){echo '<label class="col-sm-3 control-label">Тел.:</label><div class="col-sm-9"><p class="form-control-static"style="color: #FFF;background-color: #77C877; width: 94px;padding: 4px;float: left;">'.$newtext[3].' </p><span style="padding: 4px; margin-top: -1px;" class="hidee btn btn-success glyphicon glyphicon-earphone" aria-hidden="true"></span></div>';}
				if(isset($newtext[4])){echo '<label class="col-sm-3 control-label">Тел.:</label><div class="col-sm-9"><p class="form-control-static"style="color: #FFF;background-color: #77C877; width: 94px;padding: 4px;float: left;">'.$newtext[4].' </p><span style="padding: 4px; margin-top: -1px;" class="hidee btn btn-success glyphicon glyphicon-earphone" aria-hidden="true"></span></div>';}
				
				$str = str_replace($vowels, "", $klient['18']);
				$str2 = mb_strlen($str,'UTF-8')."\n";
				if($str2 == 11){
					$str00 = substr($str, 0, 1);
					$str01 = substr($str, 1, 2);
					$str02 = substr($str, 1, 3);
					$str03 = substr($str, 4, 10);
					$str04 = mysql_fetch_array(mysql_query("SELECT * FROM `mtt_codes` WHERE `def` ='".$str02."' AND `from` <= '".$str03."' AND `to` >= '".$str03."'"));
					$str05 = mysql_fetch_array(mysql_query("SELECT * FROM `mtt_regions` WHERE `id` ='".$str04['region']."'"));
					$s = $str05['tip'];
					$i = date("i");
					$H = date("H") + $str05['zch'];
					echo $str05['name'],".  Время: ",$H,":",$i;
				}
				echo '';
			}
echo '</div>
	<div class="form-group">
		<label class="col-sm-3 control-label">Пол:</label>';
		
			if(empty($klient['28'])){
				echo '<div class="col-sm-9"><div class="input-group">
					<div id="fullname-gender">
					<label class="sgt-granular_label" style="font-size: 13px; font-weight: normal;">
					<input type="radio" name="pol" id="fullname-gender-male" value="1" class="inline">
					Мужской
					</label>
					<label class="sgt-granular_label" style="
					font-size: 13px;
					font-weight: normal;
					">
					<input type="radio" name="pol" id="fullname-gender-female" value="2" class="inline">
					Женский
					</label>
					</div>
					</div></div>';
			}else{
				echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['28'].'</p></div>';
			}
echo '		
	</div>

<div id="robot" style="display: none;"> 
<p><h4>Контактное лицо <select class=""><option>Сотрудник</option><option>Заместитель</option><option>Секретарь</option><option>Бухгалтер</option><option>Программист</option><option>Юрист</option><option>Другой</option>
</select><div id="hide" style="float: right;font-size: 13px;margin-top: 7px;  cursor: pointer;">Закрыть</div></h4></p>
<div class="form-group">
<label class="col-sm-3 control-label">ФИО:</label>';
if(empty($klient['26'])){
	echo '<div class="col-sm-9"><input class="form-control col-90" type="text" placeholder="'.$klient['26'].'" aria-describedby="basic-addon1"></div>';
}else{
	echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['26'].'</p></div>';
}
echo '</div>
	<div class="form-group">
		<label class="col-sm-3 control-label">Тел:</label>';
		
			if(empty($klient['27'])){
				echo '<div class="col-sm-9">
					<div class="input-group col-90">
						<select id="str44" class="form-control" style="float: left;width: 30%;">
						<option value="str0">Рабочий</option>
						<option value="str1">Раб.прямой</option>
						<option value="str2">Мобильный</option>
						<option value="str3">Факс</option>
						<option value="str4">Городской</option>
						<option value="str5">Другй</option>
						</select>
							<input class="form-control" style="float: left;width: 70%;" type="tel" required pattern="[0-9_\-]{10}" placeholder="+7(___) ___ __ __" id="iuser_phone3" title="Формат: (096) 999 99 99">
						<span class="input-group-addon" id="basic-addon2"><a onclick="addb()"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></span>
					</div>
				</div>';
			}else{
				echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['27'].'</p></div>';
			}
echo '		
	</div>
	<div id="addbs">
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label">Пол:</label>';
		
			if(empty($klient['29'])){
				echo '<div class="col-sm-9"><input class="form-control col-90" type="text" placeholder="" aria-describedby="basic-addon1" ></div>';
			}else{
				echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['29'].'</p></div>';
			}
echo '		
	</div>';
	 
	echo'</div>
	<input type="submit" name="submitsave" style="100%" class="btn btn-success" value="Сохранить"> 
</form>';
}

if(isset($_POST['submitsave'])){
$ogrn = "INSERT INTO `ogrn` (
`d`, 
`m`, 
`y`, 
`users`, 
`inn`, 
`kpp`, 
`naim`, 
`ogrn`, 
`uridadress`, 
`fakadress`, 
`primechan`
) VALUES (
'".date('d')."', 
'".date('m')."', 
'".date('Y')."', 
'".$userdata['users_id']."', 
'$_POST[inn]', 
'$_POST[kpp]', 
'$_POST[naim]', 
'$_POST[ogrn]', 
'$_POST[uridadress]',
'$_POST[fakadress]',
'".$klient['13']."<br>".$klient['14']."'
)";
echo '1';
mysql_query($ogrn) or die(mysql_error($links));
echo '2';
$lico = "INSERT INTO `klient`(`fio`, `dol`, `tel`, `email`, `pol`) VALUES ('$_POST[fio]', '$_POST[dol]', '$_POST[tel]', '$_POST[email]', '$_POST[pol]')";
echo '3';
mysql_query($lico) or die(mysql_error($links));
echo '4';
$url2 = $wperson2['id'] + 1;
echo '5';
$url = $wperson['id'] + 1; 
echo '6';
$ogrnlico = "INSERT INTO `klient_ogrn`(`idkli`, `klient`)  VALUES ('".$url."', '".$url2."')";
echo '7';
mysql_query($ogrnlico) or die(mysql_error($links));
echo '8';
}
?>
		
		
		
		
		<br>
		<?php
		if(isset($klient['13']) || isset($klient['14'])){
		echo '<div class="panel panel-info"> <div class="panel-heading"> <h3 class="panel-title">Дополнительная информация</h3> </div> <div class="panel-body"> ';
		echo 'Коментарии 1: '.$klient['13'] .'<br>Коментарии 2: '. $klient['14'] .'<br>';
		echo 'Источник: '.$klient['6'] .'<br>';
		echo '</div> </div>';
		}
		?>
		
		
		
		
		
</div>

<div class="hidde col-md-8" style=" ">
<div class="alert alert-warning" role="alert">
      <strong><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></strong> 1. Заполните ОГРН и Ю. Адрес. Другие данные не обязательны<br>
<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span> 2. После заполнения данных выполните звонок нажав на [ <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> ] перед номером телефонва и вам будет доступна дальнейшие действия.
    </div>
	
	
	
	<div class="col-md-3">

	
	
	


	
	<?php
		if(isset($klient['13']) || isset($klient['14'])){
		echo '<br><div class="panel panel-primary"> <div class="panel-heading"> <h3 class="panel-title">Обработка</h3> </div> <div class="panel-body" style="border: 1px solid #5BC0DE;border-top: none;">
		<div class="form-group">
		<label class="col-sm-3 control-label">Продукт:</label>';
		
			if(empty($klient['4'])){
				echo '<div class="col-sm-9"><input class="form-control col-90" type="text" placeholder="" aria-describedby="basic-addon1"></div>';
			}else{
				echo '<div class="col-sm-9"><p class="form-control-static">';
				$q1z = "SELECT * FROM `produkti` WHERE id = $klient[4]";
				$result1z = mysql_query($q1z);
				$person1z = mysql_fetch_array($result1z);
				echo $person1z['name'];
				echo '</p></div>';
			}
		
	echo '</div>
	<div class="form-group">
		<label class="col-sm-3 control-label">Тариф:</label>';
		 
			if(empty($klient['5'])){
				echo '<div class="col-sm-9"><input class="form-control col-90" type="text" placeholder="" aria-describedby="basic-addon1" ></div>';
			}else{
				echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['5'].'</p></div>';
			}
		
	
		echo '</div> </div> </div>';
		}
		?>
	

 

<a onclick="namerand()"  class="btn btn-info " style="    margin-bottom: 10px;width: 100%;border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;margin-top: -10px;">Выставить счет</a>
<div id="contaicall"></div> 
<script type="text/javascript">
function namerand()
{
    var c = document.getElementById("contaicall");
    var d = document.createElement("iframe");
    var t = document.createTextNode("");
    c.appendChild(t);
    c.appendChild(d);
	d.src = "<?php echo VOOVI_MAIN_URL; ?>/newusluga.php?id=<?php echo $ogrn['id']; if(!empty($klient['11'])){ $pizza = $klient['11'];$pieces = explode("\\", $pizza);for($i=0; $i <= 10; $i++){if(!empty($pieces[$i])){echo '&dop'.$pieces[$i].'=1';}}}?>&ogrn=<?php echo $ogrn['ogrn'];?>&inn=<?php echo $ogrn['inn'];?>&kpp=<?php echo $ogrn['kpp'];?>&parent=12&tarif=<?php echo $klient['4'];?>&head=1";
	d.width = document.documentElement.clientWidth/2;
	d.height = document.documentElement.clientHeight-30;
	d.className = "iframestylecall";
	d.Name = "f2";
	document.getElementById("contaicall").className = "contaidivcall";
	// d.style.minWidth = "50%";
}
$(document).ready(function(){
    $("#contaicall").click(function(){
        $("#contaicall").empty();
		document.getElementById("contaicall").className = "";
    });
});
</script>


<?php
		if(!empty($klient['11'])){ 
		echo '<div class="panel panel-primary"> <div class="panel-heading"> <h3 class="panel-title">Доп. продукт:</h3> </div> <div class="panel-body">';
			$pizza = $klient['11'];
			$pieces = explode("\\", $pizza);
			for($i=0; $i <= 10; $i++){
				if(!empty($pieces[$i])){ 
					$r0 = mysql_query("SELECT * FROM `produkti` WHERE id = ".$pieces[$i]);
					$p0 = mysql_fetch_array($r0);
					$wissetkomment = mysql_query("SELECT COUNT(*) FROM schet WHERE inn ='".$klient['9']."' AND kpp ='".$klient['10']."' AND produkt ='".$pieces[$i]."'");
					$wyesogrn = mysql_result($wissetkomment, 0);
					echo '<div style="margin-bottom: 6px; padding: 0; " class="btn-group col-md-12 " role="group">
							<button class="btn btn-warning dropdown-toggle col-md-10" type="button" data-toggle="dropdown" aria-expanded="true" style="text-align: left;">';
					if($wyesogrn != 0){
						echo '<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> ';
					}else{
						echo '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> ';
					}	
					echo $p0['name'].' <span class="caret"></span>
							</button>
							<button class="btn btn-warning col-md-2" value="История звонков" type="button"> 
							  <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
							</button>
							<ul class="dropdown-menu" role="menu">
							  <li><a onclick="produ'.$pieces[$i].'()">Обработать</a></li>
							  <li><a onclick="namerand'.$pieces[$i].'()">Выставить счет</a></li>
							  <li class="divider"></li>
							  <li><a onclick="prod'.$pieces[$i].'()">История</a></li>
							</ul>
						  </div>
						
						<div id="contaicall'.$pieces[$i].'"></div> 
						<script type="text/javascript">
						function namerand'.$pieces[$i].'()
						{
							var c = document.getElementById("contaicall'.$pieces[$i].'");
							var d = document.createElement("iframe");
							var t = document.createTextNode("");
							c.appendChild(t);
							c.appendChild(d);
							d.src = "'.VOOVI_MAIN_URL.'/newschet.php?id='.$ogrn['id'].'&parent='.$pieces[$i].'&ogrn='.$ogrn['ogrn'].'&inn='.$ogrn['inn'].'&kpp='.$ogrn['kpp'].'&tip=12&head=1";
							d.width = document.documentElement.clientWidth/2;
							d.height = document.documentElement.clientHeight-30;
							d.className = "iframestylecall";
							d.Name = "f2";
							document.getElementById("contaicall'.$pieces[$i].'").className = "contaidivcall";
							// d.style.minWidth = "50%";
						}
						$(document).ready(function(){
							$("#contaicall'.$pieces[$i].'").click(function(){
								$("#contaicall'.$pieces[$i].'").empty();
								document.getElementById("contaicall").className = "";
							});
						});
						</script>
						  
								<script type="text/javascript">
								function prod'.$pieces[$i].'()
								{
									var docc = document.getElementById("prodtai'.$pieces[$i].'");
									var docd = document.createElement("iframe");
									var doct = document.createTextNode("11111");
									docd.appendChild(doct);
									docc.appendChild(docd);
									docd.src = "/info.php?tip=histprod&idkli='.$ogrn['id'].'&prod='.$pieces[$i].'";
									docd.width = document.documentElement.clientWidth - document.documentElement.clientWidth / 2;
									docd.height = "200px";
									docd.className = "iframestyle";
									document.getElementById("prodtai'.$pieces[$i].'").className = "contai";
								}
								$(document).ready(function(){
									$("#prodtai'.$pieces[$i].'").click(function(){
										$("#prodtai'.$pieces[$i].'").empty();
										document.getElementById("prodtai'.$pieces[$i].'").className = "";
									});
								});
								</script>
						<div id="prodtai'.$pieces[$i].'"></div>
						
						<div id="contaicall'.$pieces[$i].'"></div>
								<script type="text/javascript">
								function produ'.$pieces[$i].'()
								{
									var c = document.getElementById("contaicall'.$pieces[$i].'");
									var d = document.createElement("iframe");
									var t = document.createTextNode("<p>Закрыть окно</p>");
									c.appendChild(t);
									c.appendChild(d);
									d.src = "'.VOOVI_MAIN_URL.'/kartkliprod.php?id='.$pieces[$i].'&idkli='.$ogrn['id'].'";
									d.width = "900px";
									d.height = "350px";
									d.className = "iframestyle";
									d.Name = "f2";
									document.getElementById("contaicall'.$pieces[$i].'").className = "contaidivcall";
									// d.style.minWidth = "200px";
								}
								$(document).ready(function(){
									$("#contaicall'.$pieces[$i].'").click(function(){
										$("#contaicall'.$pieces[$i].'").empty();
										document.getElementById("contaicall'.$pieces[$i].'").className = "";
									});
								});
								</script>
						  
						  ';
				}
			}
			echo '</div></div>';
		} 
?>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne" style="background:#26BB84;color:#fff;text-align: center;padding: 7px;border-radius: 0;">
      <h4 class="panel-title" style="border:none;font-size:13px;">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Назначить задачу
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
      <form action="<?php echo $_SERVER['REQUEST_URI'];?>" method="post">
       <select  class="form-control" type="text" name="nstatus"   style="margin-bottom: 5px;" required>
		<option value="">Статус задачи</option>
		<?php 
		$query2e = mysql_query("SELECT * from call_status WHERE otk = '0'");	
		while($row2e = mysql_fetch_array($query2e)) {
			echo '<option value='.$row2e['id'].'>'.$row2e['name'].'</option>';
		}
		?>
		</select>
       <select  class="form-control" type="text" name="nuser"  style="margin-bottom: 5px;" required>
		<option value="">Контактное лицо</option>
		<?php 
		$query2 = mysql_query("SELECT * from klient_ogrn WHERE idkli = '".$ogrn['id']."' ORDER BY id DESC");	
		while($row2 = mysql_fetch_array($query2)) {
		$query3 = mysql_query("SELECT * from klient WHERE id = '".$row2['klient']."' ORDER BY id DESC");	
		while($row3 = mysql_fetch_array($query3)) {
			echo '<option>'.$row3['fio'].' ('.$row3['tel'].')</option>';
		}}
		?>
		</select>
		<input class="form-control" type="date" name="ndate" style=" float: left;     width: initial; height: 22px; margin-right:10px;" required>
		<input class="form-control" type="time" name="ntime" style=" float: left;     width: initial; height: 22px; margin-bottom:10px;" required>
		<textarea class="form-control" name="dopstat" placeholder="Описание..." rows="4" style="padding: 5px;" required></textarea>
		<input type="submit" class="btn btn-seroe" name="napominyes" value="ГОТОВО" style="max-height: 38px;  padding: 6px 10px;    border: 1px solid #dbdedf; border-bottom-width: 2px; -webkit-border-radius: 3px; -moz-border-radius: 3px;    border-radius: 3px; position: relative;  background: #fcfcfc;    background: -webkit-gradient(linear,left top,left bottom,color-stop(0,#fdfdfd),color-stop(1,#fbfbfb)); background: -webkit-linear-gradient(top,#fdfdfd,#fbfbfb); background: -moz-linear-gradient(top,#fdfdfd,#fbfbfb); background: -ms-linear-gradient(top,#fdfdfd,#fbfbfb); background: -o-linear-gradient(top,#fdfdfd,#fbfbfb); background: linear-gradient(to bottom,#fdfdfd,#fbfbfb); line-height: 19px; vertical-align: middle; color: #2e3640; text-transform: uppercase;    font-size: 13px; font-weight: bold; line-height: 14px; cursor: pointer; outline: none; position: relative;    z-index: 1;    white-space: nowrap;margin-top: 6px;">
        </form>
		<?php 
			if(isset($_POST['napominyes'])){
				echo '<br>' . $_POST['nstatus'];
				echo '<br>' . $_POST['nuser'];
				echo '<br>' . $_POST['dopstat'];
				echo '<br>' . $_POST['ndate'];
				$g = substr($_POST['ndate'], 0, 4);
				$m = substr($_POST['ndate'], 5, 2);
				$d = substr($_POST['ndate'], 8, 2);
				echo '<br>' . $_POST['ntime'];
				$ch = substr($_POST['ntime'], 0, 2);
				$mi = substr($_POST['ntime'], 3, 2);
				
				$gmd = $g.$m.$d;
				if($m == 12){
					$ygmd = $gmd + 8900;
				}else{
					$ygmd = $gmd + 100;
				}
		$saaqiq = "SELECT * FROM call_status WHERE id ='".$_POST['nstatus']."'";
		$saaqresiult = mysql_query($saaqiq);
		$saaqoigrn = mysql_fetch_array($saaqresiult);
		echo '<b>Статус: </b>'.$saaqoigrn['name'].'<br />';
				
$licoetw = "UPDATE `call_center` SET `yes`='$_POST[nstatus]',`date`='$ygmd' WHERE id ='$_GET[id]'";
mysql_query($licoetw) or die(mysql_error($links));
				echo $ygmd;
$u = "INSERT INTO `napomin` (`dr`, `mr`, `gr`, `dmg`, `gor`, `chr`, `mir`, `tipz`, `tel`, `mestvs`, `opis`, `users`,`tip`,`prod`,`statusprod`,`produrl`) VALUES ('$d', '$m', '$g', '$g$m$d', '', '$ch', '$mi', 'ssd', '$_POST[nuser]', '', '$_POST[dopstat]', '".$userdata['users_id']."', '/kartklient.php?id=', '".$klient['4']."', '".$_POST['nstatus']."', '".$ogrn['id']."')";

mysql_query($u) or die(mysql_error($link));
$aktivn = "INSERT INTO `aktivn` (`data`,`deistvie`,`users`) VALUES ('". date("d.m.Y; H:i:s") ."','Новая задача','".$userdata['users_id']."')";
mysql_query($aktivn) or die(mysql_error($link));

$aktivnw = "INSERT INTO `ogtrnprod`(`prod`, `idkli`, `date`, `text`, `kol`, `kto`, `redaktor`) VALUES ('".$klient['4']."','".$ogrn['id']."','".$g.'.'.$m.'.'.$d."','<b>Статус: </b>".$saaqoigrn['name']."<br /><b>Описание: </b>$_POST[dopstat]','','".$userdata['users_id']."','".$userdata['users_id']."')";
mysql_query($aktivnw) or die(mysql_error($link));

echo '<div class="alert alert-success">
  <strong>Удачно!</strong> Новая задача успешно добавлена.
</div>';
}
?>
	</div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo" style="background:#FF1F1F;color:#fff;text-align: center;padding: 7px;border-radius: 0;">
      <h4 class="panel-title" style="border:none;font-size:13px;">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Отказ
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
      <form action="" method="post">
        <select  class="form-control" type="text" name="potk"  style="margin-bottom: 5px;">
		<option value="">Статус отказа</option>
		<?php 
		$query2e = mysql_query("SELECT * from call_status WHERE otk = '1'");	
		while($row2e = mysql_fetch_array($query2e)) {
			echo '<option value='.$row2e['id'].'>'.$row2e['name'].'</option>';
		}
		?>
		</select>
		<textarea class="form-control" name="dpotk" placeholder="Причина отказа..." rows="4" style="padding: 5px;"></textarea>
		<input type="submit" class="btn btn-danger" name="otkazs" value="Выполнить" style="max-height: 38px;  padding: 6px 10px;    border: 1px solid #dbdedf; border-bottom-width: 2px; -webkit-border-radius: 3px; -moz-border-radius: 3px;    border-radius: 3px; position: relative;  background: #fcfcfc;    background: -webkit-gradient(linear,left top,left bottom,color-stop(0,#fdfdfd),color-stop(1,#fbfbfb)); background: -webkit-linear-gradient(top,#fdfdfd,#fbfbfb); background: -moz-linear-gradient(top,#fdfdfd,#fbfbfb); background: -ms-linear-gradient(top,#fdfdfd,#fbfbfb); background: -o-linear-gradient(top,#fdfdfd,#fbfbfb); background: linear-gradient(to bottom,#fdfdfd,#fbfbfb); line-height: 19px; vertical-align: middle; color: #2e3640; text-transform: uppercase;    font-size: 13px; font-weight: bold; line-height: 14px; cursor: pointer; outline: none; position: relative;    z-index: 1;    white-space: nowrap;margin-top: 6px;">
        </form>
		<?php 
			if(isset($_POST['otkazs'])){
                $licoetw = "UPDATE `call_center` SET `otk`='1',`potk`='$_POST[potk]($_POST[dpotk] : ".date('d.m.Y').")',`yes`='$_POST[potk]' WHERE id ='$_GET[id]'";
				mysql_query($licoetw) or die(mysql_error($links));

$saaqiq = "SELECT * FROM call_status WHERE id ='".$_POST['potk']."'";
$saaqresiult = mysql_query($saaqiq);
$saaqoigrn = mysql_fetch_array($saaqresiult);
echo '<b>Статус: </b>'.$saaqoigrn['name'].'<br />';

$g = date('Y');
$m = date('m');
$d = date('d');

$aktivnw = "INSERT INTO `ogtrnprod`(`prod`, `idkli`, `date`, `text`, `kol`, `kto`, `redaktor`) VALUES ('".$klient['4']."','".$ogrn['id']."','".$g.'.'.$m.'.'.$d."','<b>Статус: </b>".$saaqoigrn['name']."<br />$_POST[dpotk]','','".$userdata['users_id']."','".$userdata['users_id']."')";
mysql_query($aktivnw) or die(mysql_error($link));
				echo '<script type="text/javascript">
				document.location.href = "'.$_SERVER['REQUEST_URI'].'";
				</script>';
			}
			
        ?>
	</div>
    </div>
  </div>
  
  
</div>


<div style="background: #999; padding: 5px;margin-top: -10px;font-size: 13px;color: #fff;">
Звонок: +7 909 756 56-45
</div>
	<div style="background: #eee; padding: 10px; border: 1px solid #ddd;">
		<textarea class="form-control" placeholder="Добавить примечание..." rows="4" style="padding: 5px;"></textarea>
		<input type="submit" class="btn btn-seroe" value="ЗАВЕРШИТЬ ВЫЗОВ" style="  max-height: 38px;
  padding: 6px 10px;
  border: 1px solid #FF6E6E;
  background: #FF0000;
  background: -webkit-gradient(linear,left top,left bottom,color-stop(0,#FF0000),color-stop(1,#FF0000));
  background: -webkit-linear-gradient(top,#FF0000,#FF0000);
  background: -moz-linear-gradient(top,#fdfdfd,#fbfbfb);
  background: -ms-linear-gradient(top,#fdfdfd,#fbfbfb);
  background: -o-linear-gradient(top,#fdfdfd,#fbfbfb);
  background: linear-gradient(to bottom,#FF2727,#FF0000); 
  border-bottom-width: 2px;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
  position: relative;
  background: #999;
  border: 1px solid #666;
  line-height: 19px;
  vertical-align: middle;
  color: #FFFFFF;
  text-transform: uppercase;
  font-size: 13px;
  font-weight: bold;
  line-height: 14px;
  cursor: pointer;
  outline: none;
  position: relative;
  z-index: 1;
  white-space: nowrap;
  margin-top: 6px;">
	</div>
</div>
<div class="col-md-9">  
<iframe id="iframez" src="http://billy-partners.kontur.ru/Search?SearchString=<?php 
echo $ogrn['inn']; 
if(!empty($ogrn['kpp'])){
	echo '-'.$ogrn['kpp'];
}


?>" style="
    width: 50%;
    height: 97%;
    top: 40px;
    position: fixed;
    border: 0;
"></iframe>
</div>
</div>
</div> 
</div>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="js/jquery.maskedinput.min.js"></script>
<script src="js/is.mobile.js"></script>


<script>

function addb()
{
 var a = document.getElementById("addbs");
 var o = document.createElement("div");
 var b = document.createElement("label");
 var c = document.createTextNode("Тел:");
 var d = document.createElement("div");
 var j = document.createElement("div");
 var e = document.createElement("select");
 var f = document.createElement("input");
 var h = document.createElement("span");
 var i = document.createElement("span");
 a.appendChild(o);
 o.className = "form-group";
 o.appendChild(b);
 b.className = "col-sm-3 control-label";
 b.appendChild(c);
 o.appendChild(d);
 d.className = "col-sm-9";
 d.appendChild(j);
 j.appendChild(h);
 h.appendChild(i);
 h.className = "input-group-addon";
 i.className = "glyphicon glyphicon-plus";
 i.id = "glyphicon glyphicon-plus";
 j.className = "input-group col-90";
 j.appendChild(e);
 e.className = "form-control";
 e.style.float="left";
 e.style.width="30%";
 e.options[0] = new Option("Рабочий", "str0");
 e.options[1] = new Option("Раб.прямой", "str1");
 e.options[2] = new Option("Мобильный", "str2");
 e.options[3] = new Option("Факс", "str3");
 e.options[4] = new Option("Городской", "str4");
 e.options[5] = new Option("Другой", "str5");
 j.appendChild(f);
 f.className = "form-control rfield";
 f.type = "tel";
 f.style.float="left";
 f.style.width="70%";

function randomInteger(min, max) {
  var rand = min + Math.random() * (max - min)
  rand = Math.round(rand);
  return rand;
}
var s = new Date();
var azazatoha = randomInteger(10, 99) +""+ s.getSeconds();
 f.id += "user_phone" + azazatoha;
 e.id += "euserphone" + azazatoha;
	 f.pattern = "[0-9_\\-]{10}";
 f.required;
 
(function($){
	jQuery.fn.exists = function() {
	   return jQuery(this).length;
	}
$(function() {
	if(!is_mobile()){
for (var i = 0; i < 9999; i++) {
			if($('#user_phone' + i).exists()){
			$('#user_phone' + i).each(function(){
			  $(this).mask("9(999) 999-99-99");
			});
			$('#user_phone' + i)
			  .addClass('rfield')
			  .removeAttr('required')
			  .removeAttr('pattern')
			  .removeAttr('title')
			  .attr({'placeholder':'8(123) 456-78-90'});
			}
}
		$(document).ready(function(){
		for (var i = 0; i < 9999; i++) {
			$("#euserphone"+i).click(function(){
			
				if(document.getElementById('euserphone'+i).value == "str4" || document.getElementById('euserphone').value == "str3"){
				
					if($('#user_phone' + i).exists()){
					$('#user_phone' + i).each(function(){
					  $(this).mask("9(9999) 99-99-99");
					});
					$('#user_phone' + i)
					  .addClass('rfield')
					  .removeAttr('required')
					  .removeAttr('pattern')
					  .removeAttr('title')
					  .attr({'placeholder':'8(1234) 56-78-90'});
				  }
				  
				}else{
					if($('#user_phone' + i).exists()){
					$('#user_phone' + i).each(function(){
					  $(this).mask("9(999) 999-99-99");
					});
					$('#user_phone' + i)
					  .addClass('rfield')
					  .removeAttr('required')
					  .removeAttr('pattern')
					  .removeAttr('title')
					  .attr({'placeholder':'8(123) 456-78-90'});
				  }
				  }
			
			});
		}
		});
	  
	}
});
})( jQuery );



}


    //////////////////////////////////////////////////////////////////////////////////////////////////////////
	// 	<div class="form-group">                                                                            //
	//	<label class="col-sm-3 control-label">Тел:</label>                                                  //
	//	<?php                                                                                               //
	//		if(empty($klient['27'])){                                                                       //
	//			echo '<div class="col-sm-9">                                                                //
	//				<div class="input-group col-90">                                                        //
	//					<select  class="form-control" style="float: left;width: 30%;">                      //
	//						<option>Рабочий</option>                                                        //
	//						<option>Раб.прямой</option>                                                     //
	//						<option>Мобильный</option>                                                      //
	//						<option>Факс</option>                                                           //
	//						<option>Городской</option>                                                      //
	//						<option>Другой</option>                                                         //
	//					</select>                                                                           //
	//					<input class="form-control" style="float: left;width: 70%;" type="tel" required     //
	//					pattern="[0-9_\-]{10}" placeholder="+7(___) ___ __ __" id="user_phone3"              //
	//                  title="Формат: (096) 999 99 99">                                                    //
	//					<span class="input-group-addon" id="basic-addon2"><a onclick="addb()">              //
	//                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></span>        //
	//				</div>                                                                                  //
	//			</div>';                                                                                    //
	//		}else{                                                                                          //
	//			echo '<div class="col-sm-9"><p class="form-control-static">'.$klient['27'].'</p></div>';    //
	//		}                                                                                               //
	//	?>                                                                                                  //
	//</div>                                                                                                //
	//////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	
	
	(function( $ ){
	
	//// ---> Проверка на существование элемента на странице
	jQuery.fn.exists = function() {
	   return jQuery(this).length;
	}
	
	//	Phone Mask
	$(function() {
		
    if(!is_mobile()){
	
	

 for (var i = 0; i < 9999; i++) {
      if($('#iuser_phone' + i).exists()){
        $('#iuser_phone' + i).each(function(){
          $(this).mask("9(999) 999-99-99");
        });
        $('#iuser_phone' + i)
          .addClass('rfield')
          .removeAttr('required')
          .removeAttr('pattern')
          .removeAttr('title')
          .attr({'placeholder':'8(123) 456-78-90'});
      }
      }
 $(document).ready(function()
{
 $("#str44").click(function()
{
 if(document.getElementById('str44').value == "str4" || document.getElementById('str44').value == "str3"){
 for (var i = 0; i < 9999; i++) {
      if($('#iuser_phone' + i).exists()){
        $('#iuser_phone' + i).each(function(){
          $(this).mask("9(9999) 99-99-99");
        });
        $('#iuser_phone' + i)
          .addClass('rfield')
          .removeAttr('required')
          .removeAttr('pattern')
          .removeAttr('title')
          .attr({'placeholder':'8(1234) 56-78-90'});
      }
      }
      }else{
	  for (var i = 0; i < 9999; i++) {
	        if($('#iuser_phone' + i).exists()){
        $('#iuser_phone' + i).each(function(){
          $(this).mask("9(999) 999-99-99");
        });
        $('#iuser_phone' + i)
          .addClass('rfield')
          .removeAttr('required')
          .removeAttr('pattern')
          .removeAttr('title')
          .attr({'placeholder':'8(123) 456-78-90'});
      }
	  }
	  }
	  });
	  });
    
} 
	});

})( jQuery );


	
</script>

<script>
$('#hide').click(function(){
  $('#robot').hide('slow');
  $('#show').show();
  $('#hide').hide();
});
$('#show').click(function(){
  $('#robot').show('slow');
  $('#show').hide();
  $('#hide').show();
});
$('.hidee').click(function(){
  $('.hidde').hide();
});
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>
