<?php
include 'conf.php';  
if (isset($_COOKIE['id']) and isset($_COOKIE['hash'])) 
{
$userdata = mysql_fetch_assoc(mysql_query("SELECT * FROM users WHERE users_id = '".intval($_COOKIE['id'])."' LIMIT 1"));if(($userdata['users_hash'] !== $_COOKIE['hash']) or ($userdata['users_id'] !== $_COOKIE['id'])) 
{ 
setcookie('id', '', time() - 60*24*30*12, '/'); 
setcookie('hash', '', time() - 60*24*30*12, '/');
setcookie('errors', '1', time() + 60*24*30*12, '/'); 
header('Location: index.php'); exit();
} 
} 
else 
{ 
  setcookie('errors', '2', time() + 60*24*30*12, '/');
  header('Location: index.php'); exit();
}
$aaqiq = "SELECT * FROM produkti WHERE id ='".$_GET['id']."'";
$aaqresiult = mysql_query($aaqiq);
$aaqoigrn = mysql_fetch_array($aaqresiult);

$result = mysql_query("SELECT COUNT(*) FROM ogtrnprod WHERE prod ='".$_GET['id']."' AND idkli ='".$_GET['idkli']."'");
$class = mysql_result($result, 0);
$aqiq = "SELECT * FROM ogtrnprod WHERE prod ='".$_GET['id']."' AND idkli ='".$_GET['idkli']."'  ORDER BY id DESC";
$aqresiult = mysql_query($aqiq);
$aqoigrn = mysql_fetch_array($aqresiult);
 ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
<meta http-equiv="content-type" content="text/html" charset="utf-8" />
<link href="css/bootstrap.min.css" rel="stylesheet">
<meta name="description" content="An Icon Font Generated By IcoMoon.io">
<meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="style.css"> 
<link href="https://dadata.ru/static/css/lib/suggestions-4.8.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="https://dadata.ru/static/js/lib/jquery.suggestions-4.8.min.js"></script>
</head>
<body style="background: #F5F5F5;color: #666;">
<div style="margin-bottom: 8px;font-size: 18px;background: #3b5998;padding: 5px 13px;color: #fff;">
Продукт "<?php echo $aaqoigrn['name']; ?>"
</div>
<div class="container">
<div class="row">
<?php 
if(isset($_POST['submit'])){
if ($class == 0) {
$aktivn = "INSERT INTO `ogtrnprod`(`prod`, `idkli`, `date`, `text`, `kol`, `kto`, `redaktor`) VALUES ('".$_GET['id']."','".$_GET['idkli']."','".$_POST['date']."','".$_POST['text']."','".$_POST['kol']."','".$_POST['users']."','".$userdata['users_id']."')";
mysql_query($aktivn) or die(mysql_error($link));

echo 'Добавление коментарий выполненно
<script>
$(this).val(newContent);
</script>
';
}else{
$aktivn = "INSERT INTO `ogtrnprod`(`prod`, `idkli`, `date`, `text`, `kol`, `kto`, `redaktor`) VALUES ('".$_GET['id']."','".$_GET['idkli']."','".$_POST['date']."','".$_POST['text']."','".$_POST['kol']."','".$aqoigrn['kto']."','".$userdata['users_id']."')";
mysql_query($aktivn) or die(mysql_error($link));

echo 'Добавление коментарий выполненно
<script>
$(this).val(newContent);
</script>
';
}

 

if(isset($_POST['check'])){
$u = "INSERT INTO `napomin` (`dr`, `mr`, `gr`, `dmg`, `gor`, `chr`, `mir`, `tipz`, `tel`, `mestvs`, `opis`, `users`, `produrl`, `prod`, `tip`) VALUES 
('$_POST[dr]', '$_POST[mr]', '$_POST[gr]', '$_POST[gr]$_POST[mr]$_POST[dr]', '$_POST[gor]', '$_POST[chr]', '$_POST[mir]', 'ssd', '*', '*', '".$_POST['text']."', '".$_POST['users']."', '".$_GET['idkli']."', '".$_GET['id']."', '/kartklient.php?id=')";
mysql_query($u) or die(mysql_error($link));
echo $link;
$aktivnl = "INSERT INTO `aktivn` (`data`,`deistvie`,`users`) VALUES ('". date("d.m.Y; H:i:s") ."','Новая задача','".$userdata['users_id']."' Для ','".$_POST['users']."')";
mysql_query($aktivnl) or die(mysql_error($link));
}



}
?>
<form class="form-horizontal"  method="post">
<div class="form-group">
<label class="col-sm-2 control-label">Дата предложения:</label><div class="col-sm-10"><input name="date" type="date" value="<?php if(!empty($aqoigrn['date'])){echo $aqoigrn['date'];}else{echo date('Y-m-d');} ?>"></div>		
</div>
<div class="form-group">
<label class="col-sm-2 control-label">Коментарий:</label><div class="col-sm-10"><textarea name="text" style="width:100%;" rows="8"><?php echo $aqoigrn['text']; ?></textarea></div>		
</div>
<div class="form-group">
<label class="col-sm-2 control-label">Рабочих мест:</label><div class="col-sm-10"><input name="kol" type="number" value="<?php echo $aqoigrn['kol']; ?>"></div>		
</div>
 <div class="form-group" style="
    float: left;
    margin-left: 100px;
    width: 229px;
">
    <label  class="col-sm-2 control-label"></label>
    <label  class="col-sm-10">
      <input  class="" name="check"  id = 'cb1' onchange = 'showOrHide("cb1", "cat1");' type="checkbox"  checked="checked"> Создать напоминание 
    </label>
  </div>
  <script>
function showOrHide(cb, cat) {
    cb = document.getElementById(cb);
    cat = document.getElementById(cat);
    if (cb.checked) cat.style.display = "block";
    else cat.style.display = "none";
  }
</script>
<div style="margin-top: 6px;margin-left: 20%;"  id="cat1" style="display:none;">

<select type="text" name="users" style="float: left;" />
<option value="<?php echo $userdata['users_id']; ?>"><?php echo $userdata['f_name']," ",$userdata['l_name']; ?></option>
<?php
$querysas = mysql_query("SELECT * from users WHERE users_id != '".$userdata['users_id']."' AND tip != '88'");
while($rowsas = mysql_fetch_array($querysas)) {
echo "<option value='".$rowsas['users_id']."'>";
echo $rowsas['f_name']," ",$rowsas['l_name'];
echo "</option>";
}?>

</select><br><br>

<span>Дата:</span>
<select style="margin-bottom: 0px;"  type="text" name="dr"  />
<option value="<?php echo date("d"); ?>"><?php echo date("d"); ?></option>
<option>01</option>
<option>02</option>
<option>03</option>
<option>04</option>
<option>05</option>
<option>06</option>
<option>07</option>
<option>08</option>
<option>09</option>
<?php 
$a = 10;
$b = date("t");
while($a <= $b) echo '<option>',$a++,'</option>';
?>
</select>
<span >:</span>
<select style="margin-bottom: 0px;"  type="text" name="mr"  />
<option value="<?php echo date("m"); ?>">
<?php 
if (date("m") == "01") {
echo "Январь"; 
} if (date("m") == "02") {
echo "Февраль"; 
} if (date("m") == "03") {
echo "Март"; 
} if (date("m") == "04") {
echo "Апрель"; 
} if (date("m") == "05") {
echo "Май"; 
} if (date("m") == "06") {
echo "Июнь"; 
} if (date("m") == "07") {
echo "Июль"; 
} if (date("m") == "08") {
echo "Август"; 
} if (date("m") == "09") {
echo "Сентябрь"; 
} if (date("m") == "10") {
echo "Октябрь"; 
} if (date("m") == "11") {
echo "Ноябрь"; 
} if (date("m") == "12") {
echo "Декабрь"; 
}
?>
</option>
  <option value="01">Январь</option>
  <option value="02">Февраль</option>
  <option value="03">Март</option>
  <option value="04">Апрель</option>
  <option value="05">Май</option>
  <option value="06">Июнь</option>
  <option value="07">Июль</option>
  <option value="08">Август</option>
  <option value="09">Сентябрь</option>
  <option value="10">Октябрь</option>
  <option value="11">Ноябрь</option>
  <option value="12">Декабрь</option>
</select><span >:</span>
<select style="margin-bottom: 0px;" type="text" name="gr"  />
  <option value="2015">2015</option>
  <option value="2016">2016</option>
  <option value="2017">2017</option>
  <option value="2018">2018</option>
  <option value="2019">2019</option>
  <option value="2020">2020</option>
  <option value="2021">2021</option>
  <option value="2022">2022</option>
  <option value="2023">2023</option>
</select><span >Время:</span>
<select style="margin-bottom: 0px;"  type="text" name="chr"  />
<option value="<?php echo date("H"); ?>"><?php echo date("H"); ?></option>
  <option value="01">01</option>
  <option value="02">02</option>
  <option value="03">03</option>
  <option value="04">04</option>
  <option value="05">05</option>
  <option value="06">06</option>
  <option value="07">07</option>
  <option value="08">08</option>
  <option value="09">09</option>
  <option value="10">10</option>
  <option value="11">11</option>
  <option value="12">12</option>
  <option value="13">13</option>
  <option value="14">14</option>
  <option value="15">15</option>
  <option value="16">16</option>
  <option value="17">17</option>
  <option value="18">18</option>
  <option value="19">19</option>
  <option value="20">20</option>
  <option value="21">21</option>
  <option value="22">22</option>
  <option vclue="23">23</option>
  <option value="24">24</option>
</select><span>:</span>
<select style="margin-bottom: 0px;" type="text" name="mir"  />
<option value="<?php echo date("i"); ?>"><?php echo date("i"); ?></option>
<option value="00">00</option>
<option value="05">05</option>
<option value="10">10</option>
  <option value="15">15</option>
  <option value="20">20</option>
  <option value="25">25</option>
  <option value="30">30</option>
  <option value="35">35</option>
  <option value="40">40</option>
  <option value="45">45</option>
  <option value="50">50</option>
  <option value="55">55</option>
</select>
</div>
<div class="form-group">
<input type="submit" name="submit" class="btn btn-success col-md-12" value="Выполнить">
</div>
</form>

</div>
</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>