<?php
include 'conf.php';
if (isset($_COOKIE['id']) and isset($_COOKIE['hash']))
{
$userdata = mysql_fetch_assoc(mysql_query("SELECT * FROM users WHERE users_id = '".intval($_COOKIE['id'])."' LIMIT 1"));if(($userdata['users_hash'] !== $_COOKIE['hash']) or ($userdata['users_id'] !== $_COOKIE['id']))
{
setcookie('id', '', time() - 60*24*30*12, '/');
setcookie('hash', '', time() - 60*24*30*12, '/');
setcookie('errors', '1', time() + 60*24*30*12, '/');
header('Location: index.php'); exit();
}
}
else
{
  setcookie('errors', '2', time() + 60*24*30*12, '/');
  header('Location: index.php'); exit();
}
$aaqiq = "SELECT * FROM produkti WHERE id ='".$_GET['id']."'";
$aaqresiult = mysql_query($aaqiq);
$aaqoigrn = mysql_fetch_array($aaqresiult);

$result = mysql_query("SELECT COUNT(*) FROM ogtrnprod WHERE prod ='".$_GET['id']."' AND idkli ='".$_GET['idkli']."'");
$class = mysql_result($result, 0);
$aqiq = "SELECT * FROM ogtrnprod WHERE prod ='".$_GET['id']."' AND idkli ='".$_GET['idkli']."'  ORDER BY id DESC";
$aqresiult = mysql_query($aqiq);
$aqoigrn = mysql_fetch_array($aqresiult);
 ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
<meta http-equiv="content-type" content="text/html" charset="utf-8" />
<link href="css/bootstrap.min.css" rel="stylesheet">
<meta name="description" content="An Icon Font Generated By IcoMoon.io">
<meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="style.css">
<link href="https://dadata.ru/static/css/lib/suggestions-4.8.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="https://dadata.ru/static/js/lib/jquery.suggestions-4.8.min.js"></script>

<style>
.iframestyle {
    position: absolute;
    background: #fff;
    left: 50%;
    margin: 50px -450px;
    border-radius: 7px;
    border: 0px solid #333;
    padding: 11px;
    box-shadow: 0 0 10px #333;
}
.contaidivcall {
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    background: rgb(185, 185, 185);
    z-index: 9999;
    text-align: center;
    font-size: 17px;
    line-height: 48px;
    cursor: pointer;
    font-weight: bold;
    color: #8c8c8c;
}
</style >
</head>
<body style="background: #F5F5F5;color: #666;">

<div class="">
<div class="row">



	<table class="table tablehover">
	<thead>
        <tr>
		  <th  style="width: 160px; ">Продукт</th>
		  <th  style="width: 80px; ">Дата</th>
		  <th>Коментарии</th>
		  <th style="width: 1px;">Комп</th>
		  <th style="width: 1px;"><span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span></th>
        </tr>
    </thead>
					<?php

						$num = 100;
						$page = $_GET['page'];
						$result00 = mysql_query("SELECT COUNT(*) FROM produkti WHERE kartkli = '1'");
						$temp = mysql_fetch_array($result00);
						$posts = $temp[0];
						$total = (($posts - 1) / $num) + 1;
						$total =  intval($total);
						$page = intval($page);
						if(empty($page) or $page < 0) $page = 1;
						if($page > $total) $page = $total;
						$start = $page * $num - $num;


						$query = mysql_query("SELECT * from produkti  ORDER BY id ASC");
							while($row = mysql_fetch_array($query)) {
							if($row['parent'] == $userdata['inogrn']) {


							$aqiq = "SELECT * FROM ogtrnprod WHERE prod ='".$row['id']."' AND idkli ='".$_GET['id']."' ORDER BY id DESC";
						$aqresiult = mysql_query($aqiq);
						$aqoigrn = mysql_fetch_array($aqresiult);

								echo '<tr   style="font-size: 12px;"  id="disp"><td style="width: 160px;">';
								echo $row['name'];
								echo '</td>';
								echo '<td style="width: 180px;" ';
								echo 'onclick="ktoprodu'.$row['id'].'()"';
								echo '>';

								if(!empty($aqoigrn['kto'])){
								echo $aqoigrn['date']." <br> ";
								$usersaqiq = "SELECT * FROM users WHERE users_id ='".$aqoigrn['kto']."'";
								$usersaqresiult = mysql_query($usersaqiq);
								$usersaqoigrn = mysql_fetch_array($usersaqresiult);
								if(!empty($usersaqoigrn['f_name'])){
								echo '<div id="kakadu'.$row['id'].'">'.$usersaqoigrn['f_name']." ".$usersaqoigrn['l_name'].'</div>';
								}else{
								echo 'Я незнаю';
								}
								if($aqoigrn['kto'] == $userdata['users_id']){
								echo '<select ';
								echo 'onchange="ktoProduu'.$row['id'].'(this.value)"';
								echo ' id="ktoprodu'.$row['id'].'" style="display: none;" >';
								echo "<option></option>";
									$querysas = mysql_query("SELECT * from users WHERE users_id != '".$userdata['users_id']."' AND tip != '88'");
									while($rowsas = mysql_fetch_array($querysas)) {
									echo "<option value='".$rowsas['users_id']."'>";
									echo $rowsas['f_name']," ",$rowsas['l_name'];
									echo '</option>
									';
									}
								echo '</select>
								<script>
										function ktoprodu'.$row['id'].'()
										{
											document.getElementById("ktoprodu'.$row['id'].'").style.display="block";
										}
										function ktoProduu'.$row['id'].'(str)
										{
												$.ajax({
													type: "GET",
													url: "pusya.php",
													data: "lico="+str+"&tip=ktoprodu&idkli='.$_GET['id'].'&prod='.$row['id'].'",
													success: function(msg){
														$("#kakadu'.$row['id'].'").html(msg);
														document.getElementById("ktoprodu'.$row['id'].'").style.display="none";
													}
												});
										}
								</script>';
								} else if($userdata['otvetstven']=='1') {
									echo '<select ';
								echo 'onchange="ktoProduu'.$row['id'].'(this.value)"';
								echo ' id="ktoprodu'.$row['id'].'" style="display: none;" >';
								echo "<option></option>";
									$querysas = mysql_query("SELECT * from users WHERE users_id != '".$userdata['users_id']."' AND tip != '88'");
									while($rowsas = mysql_fetch_array($querysas)) {
									echo "<option value='".$rowsas['users_id']."'>";
									echo $rowsas['f_name']," ",$rowsas['l_name'];
									echo '</option>
									';
									}
								echo '</select>
								<script>
										function ktoprodu'.$row['id'].'()
										{
											document.getElementById("ktoprodu'.$row['id'].'").style.display="block";
										}
										function ktoProduu'.$row['id'].'(str)
										{
												$.ajax({
													type: "GET",
													url: "pusya.php",
													data: "lico="+str+"&tip=ktoprodu&idkli='.$_GET['id'].'&prod='.$row['id'].'",
													success: function(msg){
														$("#kakadu'.$row['id'].'").html(msg);
														document.getElementById("ktoprodu'.$row['id'].'").style.display="none";
													}
												});
										}
								</script>';
								}
								}



								echo '</td>';
								echo '<td>';
								echo $aqoigrn['text'];

if($aqoigrn['redaktor'] > '0'){
									$wusersaqiq = "SELECT * FROM users WHERE users_id ='".$aqoigrn['redaktor']."'";
									$wusersaqresiult = mysql_query($wusersaqiq);
									$wusersaqoigrn = mysql_fetch_array($wusersaqresiult);

									echo ' <i> ('.$wusersaqoigrn['f_name']." ".$wusersaqoigrn['l_name'].')</i>';
								}

								$resulte = mysql_query("SELECT COUNT(*) FROM ogtrnprod WHERE prod ='".$row['id']."' AND idkli ='".$_GET['id']."'");
								$classe = mysql_result($resulte, 0);
								if($classe > '1'){
									echo '<span onclick="prod'.$row['id'].'()" style="float:right;" class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>

									<script type="text/javascript">
									function prod'.$row['id'].'()
									{
										var docc = document.getElementById("prodtai'.$row['id'].'");
										var docd = document.createElement("iframe");
										var doct = document.createTextNode("11111");
										docd.appendChild(doct);
										docc.appendChild(docd);
										docd.src = "/info.php?tip=histprod&idkli='.$_GET['id'].'&prod='.$row['id'].'";
										docd.width = document.documentElement.clientWidth - document.documentElement.clientWidth / 2;
										docd.height = "200px";
										docd.className = "iframestyle";
										document.getElementById("prodtak'.$row['id'].'").className = "contai";
									}
									$(document).ready(function(){
										$("#prodtai'.$row['id'].'").click(function(){
											$("#prodtai'.$row['id'].'").empty();
											document.getElementById("prodtai'.$row['id'].'").className = "";
										});
									});
									</script>
									<div id="prodtai'.$row['id'].'"></div>';
								}

								echo '</td>';
								echo '<td>';
								echo $aqoigrn['kol'];
								echo '</td>';
								echo '<td ';
								echo 'onclick="produ'.$row['id'].'()"';
								echo' id="produ'.$row['id'].'" style="width: 1px;">';
								echo '<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>';
								echo '</td></tr>';
								echo '<div id="contaicall"></div>
									<script type="text/javascript">

									function produ'.$row['id'].'()
									{
										var c = document.getElementById("contaicall");
										var d = document.createElement("iframe");
										var t = document.createTextNode("Закрыть и перейти к списку");
										c.appendChild(t);
										c.appendChild(d);
										d.src = "'.VOOVI_MAIN_URL.'/kartkliprod.php?id='.$row['id'].'&idkli='.$_GET['id'].'";
										d.width = "900px";
										d.height = "450px";
										d.className = "iframestyle";
										d.Name = "f2";
										document.getElementById("contaicall").className = "contaidivcall";
										// d.style.minWidth = "200px";
									}
									$(document).ready(function(){
										$("#contaicall").click(function(){
											$("#contaicall").empty();
											document.getElementById("contaicall").className = "";
											 document.location.href = "/kliprodpage.php?id='.$_GET['id'].'";
										});
									});
									</script>';


															}
															}
					?>
				</table>




</div>
</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>
